### PR TITLE
Windows port of muon

### PR DESCRIPTION
**Pull request by vtorri**

### CODE REVIEW

**Comment by Tachi107** [comment]
I think that muon doesn't accept PRs on GitHub, but only patches on the sourcehut mailing list

**Comment by vtorri** [comment]
@Tachi107 I know, but we discussed, (Stone Tickle and I), about this. PR are easier for me. Once the windows port is in a good shape, it will be possible to get the patch and send it to sourcehut. The port is not finished. There are a lot of stuff to fix.

**Comment by Tachi107** [comment]
Il giorno dom 2 ott 2022 alle 11:21:56 -07:00:00, vtorri 
***@***.***> ha scritto:
> @Tachi107 I know, but we discussed, (Stone Tickle and I), about this. 
> PR are easier for me. Once the windows port is in a good shape, it 
> will be possible to get the patch and send it to sourcehut. The port 
> is not finished. There are a lot of stuff to fix.
> 

Okay, thanks for the explanation :)

-- 
OpenPGP key: 66DE F152 8299 0C21 99EF  A801 A8A1 28A8 AB1C EE49

**Comment by annacrombie** [comment]
merged

**Pull request closed without merging**
